# Generated by Django 4.0.4 on 2022-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_earned',
            field=models.FloatField(default=0.0),
        ),
    ]

